Repository OT-CONTAINER-KIT/redis-operator, pull requests merged in 2022-10, with the labels that each got.

#344 [BugFix]Fixed IP check logic for conversion
  k8sutils/redis.go
Labels: hacktoberfest-accepted

#345 [BugFix]Fixed issue for redis persistence
  api/v1beta1/rediscluster_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/redis.redis.opstreelabs.in_redisclusters.yaml
  k8sutils/redis-cluster.go
Labels: hacktoberfest-accepted

#346 [Add]Added code for statefulset finalizer
  k8sutils/finalizer.go
Labels: hacktoberfest-accepted

#348 [BugFix]Added prometheus service annotation
  k8sutils/labels.go
Labels: hacktoberfest-accepted

#349 [Development][Add] Added support for redis v7
  CHANGELOG.md
  SECURITY.md
  api/v1beta1/rediscluster_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/redis.redis.opstreelabs.in_redisclusters.yaml
  docs/src/guide/README.md
  docs/src/guide/changelog.md
  docs/src/guide/failover.md
  docs/src/guide/installation.md
  docs/src/guide/redis-cluster-config.md
  docs/src/guide/redis-config.md
  example/advance_config/clusterd.yaml
  example/advance_config/standalone.yaml
  example/affinity/clusterd.yaml
  example/affinity/standalone.yaml
  example/disruption_budget/clusterd.yaml
  example/eks-cluster.yaml
  example/external_config/clusterd.yaml
  example/external_config/standalone.yaml
  example/external_service/clusterd.yaml
  example/external_service/standalone.yaml
  example/password_protected/clusterd.yaml
  example/password_protected/standalone.yaml
  example/private_registry/clusterd.yaml
  example/private_registry/standalone.yaml
  example/probes/clusterd.yaml
  example/probes/standalone.yaml
  example/redis-cluster.yaml
  example/redis-standalone.yaml
  example/redis_monitoring/cluster.yaml
  example/redis_monitoring/clusterd.yaml
  example/redis_monitoring/standalone.yaml
  example/tls_enabled/redis-cluster.yaml
  example/tls_enabled/redis-standalone.yaml
  k8sutils/redis.go
  k8sutils/statefulset.go
Labels: hacktoberfest-accepted

#353 [Development][Add] Added option to pause reconcilations
  Makefile
  controllers/redis_controller.go
  controllers/rediscluster_controller.go
  example/redis_monitoring/clusterd.yaml
  example/redis_monitoring/standalone.yaml
Labels: enhancement, hacktoberfest-accepted

#356 [BugFix][Add] Added build arg for arm64 support
  Dockerfile
Labels: enhancement, hacktoberfest-accepted

#361 fix: lost replications when followerReplicas bigger than leaderReplicas
  .gitignore
  k8sutils/redis.go
Labels: enhancement

#365 [Documentation]Renamed the external config to additional config
  example/additional_config/clusterd.yaml
  example/additional_config/configmap.yaml
  example/additional_config/standalone.yaml
Labels: documentation

#366 [BugFix]Updated the security context for controller manager
  config/manager/manager.yaml
Labels: bug

#367 [Development][Add] Added logic for updating followers replicas
  controllers/rediscluster_controller.go
Labels: bug, hacktoberfest-accepted

#369 [Development][Change] Change ctrl time for errors
  controllers/rediscluster_controller.go
  example/eks-cluster.yaml
Labels: enhancement, hacktoberfest-accepted
