Repository OT-CONTAINER-KIT/redis-operator, pull requests merged in 2023-10, with the labels that each got.

#653 Golang ci lint action
  .github/workflows/operator-ci.yaml
  api/v1beta2/redis_webhook.go
  api/v1beta2/rediscluster_webhook.go
  api/v1beta2/redisreplication_webhook.go
  api/v1beta2/redissentinel_webhook.go
  controllers/redis_controller.go
  controllers/rediscluster_controller.go
  controllers/redisreplication_controller.go
  controllers/redissentinel_controller.go
  k8sutils/poddisruption.go
  k8sutils/redis.go
  k8sutils/services.go
  k8sutils/statefulset.go
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#658 Fix e2e test
  tests/e2e/v1beta2/setup/ready-cluster.yaml
  tests/readme.md
Labels: documentation

#662 [Fix] - make deploy target not works well
  Makefile
  api/rbac.go
  config/certmanager/certificate.yaml
  config/crd/bases/redis.redis.opstreelabs.in_redis.yaml
  config/crd/bases/redis.redis.opstreelabs.in_redisclusters.yaml
  config/crd/bases/redis.redis.opstreelabs.in_redisreplications.yaml
  config/crd/bases/redis.redis.opstreelabs.in_redissentinels.yaml
  config/crd/patches/webhook_in_redis.yaml
  config/crd/patches/webhook_in_redisclusters.yaml
  config/crd/patches/webhook_in_redisreplications.yaml
  config/crd/patches/webhook_in_redissentinels.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/prometheus/monitor.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/webhook/service.yaml
Labels: bug

#664 [Fix] : deploy can not set custom image:tag
  .github/workflows/e2e.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
Labels: bug

#666 [Feat] : support ignore specify annotation key in statefulset
  .github/workflows/e2e.yaml
  api/common_types.go
  config/crd/bases/redis.redis.opstreelabs.in_redis.yaml
  config/crd/bases/redis.redis.opstreelabs.in_redisclusters.yaml
  config/crd/bases/redis.redis.opstreelabs.in_redisreplications.yaml
  config/crd/bases/redis.redis.opstreelabs.in_redissentinels.yaml
  k8sutils/labels.go
  k8sutils/labels_test.go
  k8sutils/poddisruption.go
  k8sutils/redis-cluster.go
  k8sutils/redis-replication.go
  k8sutils/redis-sentinel.go
  k8sutils/redis-standalone.go
  k8sutils/statefulset.go
  tests/_config/kuttl-test.yaml
  tests/e2e/v1beta2/ignore-annots/redis-cluster/00-install.yaml
  tests/e2e/v1beta2/ignore-annots/redis-cluster/cluster.yaml
  tests/e2e/v1beta2/ignore-annots/redis-cluster/ignore-annots-sts.yaml
  tests/e2e/v1beta2/ignore-annots/redis-cluster/ready-cluster-sts.yaml
  tests/e2e/v1beta2/ignore-annots/redis-cluster/ready-cluster.yaml
  tests/e2e/v1beta2/ignore-annots/redis-cluster/ready-pvc.yaml
  tests/e2e/v1beta2/ignore-annots/redis-standalone/00-install.yaml
  tests/e2e/v1beta2/ignore-annots/redis-standalone/ignore-annots-sts.yaml
  tests/e2e/v1beta2/ignore-annots/redis-standalone/ready-pvc.yaml
  tests/e2e/v1beta2/ignore-annots/redis-standalone/ready-standalone.yaml
  tests/e2e/v1beta2/ignore-annots/redis-standalone/ready-sts.yaml
  tests/e2e/v1beta2/ignore-annots/redis-standalone/standalone.yaml
Labels: enhancement

#670 [Fix] : redis exporter mismatch environment
  k8sutils/statefulset.go
  k8sutils/statefulset_test.go
Labels: bug

#679 [Fix] : setup label redis_setup_type to sentinel
  k8sutils/redis-sentinel.go
  tests/e2e/v1beta2/setup/redis-sentinel/00-install.yaml
  tests/e2e/v1beta2/setup/redis-sentinel/ready-sts.yaml
  tests/e2e/v1beta2/setup/redis-sentinel/ready-svc.yaml
  tests/e2e/v1beta2/setup/redis-sentinel/sentinel.yaml
Labels: bug

#680 [Fix] : wait follower statefulset ready before make cluster
  controllers/rediscluster_controller.go
Labels: bug
